namespace Rogium.Editors.Core.Defaults
{
    /// <summary>
    /// Contains default values of <see cref="ParameterInfo"/> for assets.
    /// </summary>
    public static class ParameterDefaults
    {
        public static readonly ParameterInfo ParamsTile = new ParameterInfo(intValue1: 1,
                                                                            intValue2: 2,
                                                                            intValue3: 3,
                                                                            intValue4: 4,
                                                                            intValue5: 0,
                                                                            intValue6: 0,
                                                                            floatValue1: 0,
                                                                            floatValue2: 0,
                                                                            floatValue3: 0,
                                                                            floatValue4: 0,
                                                                            floatValue5: 0,
                                                                            floatValue6: 0,
                                                                            boolValue1: false,
                                                                            boolValue2: false,
                                                                            boolValue3: false,
                                                                            boolValue4: false,
                                                                            boolValue5: false,
                                                                            boolValue6: false,
                                                                            stringValue1: "",
                                                                            stringValue2: "",
                                                                            stringValue3: "",
                                                                            stringValue4: "",
                                                                            stringValue5: "",
                                                                            stringValue6: "");
        
        public static readonly ParameterInfo ParamsEnemy = new ParameterInfo(intValue1: 0,
                                                                             intValue2: 0,
                                                                             intValue3: 0,
                                                                             intValue4: 0,
                                                                             intValue5: 0,
                                                                             intValue6: 0,
                                                                             floatValue1: 0,
                                                                             floatValue2: 0,
                                                                             floatValue3: 0,
                                                                             floatValue4: 0,
                                                                             floatValue5: 0,
                                                                             floatValue6: 0,
                                                                             boolValue1: false,
                                                                             boolValue2: false,
                                                                             boolValue3: false,
                                                                             boolValue4: false,
                                                                             boolValue5: false,
                                                                             boolValue6: false,
                                                                             stringValue1: "",
                                                                             stringValue2: "",
                                                                             stringValue3: "",
                                                                             stringValue4: "",
                                                                             stringValue5: "",
                                                                             stringValue6: "");
        
        public static readonly ParameterInfo ParamsEmpty = new ParameterInfo(intValue1: 0,
                                                                             intValue2: 0,
                                                                             intValue3: 0,
                                                                             intValue4: 0,
                                                                             intValue5: 0,
                                                                             intValue6: 0,
                                                                             floatValue1: 0,
                                                                             floatValue2: 0,
                                                                             floatValue3: 0,
                                                                             floatValue4: 0,
                                                                             floatValue5: 0,
                                                                             floatValue6: 0,
                                                                             boolValue1: false,
                                                                             boolValue2: false,
                                                                             boolValue3: false,
                                                                             boolValue4: false,
                                                                             boolValue5: false,
                                                                             boolValue6: false,
                                                                             stringValue1: "",
                                                                             stringValue2: "",
                                                                             stringValue3: "",
                                                                             stringValue4: "",
                                                                             stringValue5: "",
                                                                             stringValue6: "");
    }
}